# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Build and Push Docker Images
description: Build and push docker images with buildx, using the build script

inputs:
  github-token:
    description: "A PAT to authenticate with Github"
    required: false
  build-parent:
    description: "Whether to build parent image first"
    required: false
    default: 'false'
  build-latest:
    description: "Latest Build"
    required: false
    default: 'false'
  registry-username:
    description: "The Image Registry Username"
    required: false
  registry-password:
    description: "The Image Registry Password or Token"
    required: false
  docker-login:
    description: "Require Docker Login"
    required: false
    default: 'false'
  debug:
    description: "Debug Build"
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Build Base
      if: ${{ inputs.build-parent == 'true' }}
      shell: bash
      env:
        GH_CLIENT_TOKEN: "${{ inputs.github-token }}"
        REGISTRY_USERNAME: "${{ inputs.registry-username }}"
        REGISTRY_PASSWORD: "${{ inputs.registry-password }}"
        DOCKER_LOGIN: "${{ inputs.docker-login }}"
        LATEST: ${{ inputs.build-latest }}
        DEBUG: ${{ inputs.debug }}
      run: bin/build.sh -B -N

    - name: Build Main
      if: ${{ inputs.build-parent != 'true' }}
      shell: bash
      env:
        GH_CLIENT_TOKEN: "${{ inputs.github-token }}"
        REGISTRY_USERNAME: "${{ inputs.registry-username }}"
        REGISTRY_PASSWORD: "${{ inputs.registry-password }}"
        DOCKER_LOGIN: "${{ inputs.docker-login }}"
        LATEST: ${{ inputs.build-latest }}
        DEBUG: ${{ inputs.debug }}
      run: bin/build.sh -N
