#!/usr/bin/env sh

set -euf
LC_TYPE=C

echo
printf "\033[92;1m>>>\033[94;1m%s\033[92;1m <<<\033[0m\n" "Docker Hub Login Script"

REGISTRY_USERNAME="${REGISTRY_USERNAME:-""}"
REGISTRY_PASSWORD="${REGISTRY_PASSWORD:-""}"

if [ -z "$REGISTRY_USERNAME" -o -z "$REGISTRY_PASSWORD" ]; then
    printf ""
    while [ -z "$REGISTRY_USERNAME" ]; do
        printf "Username: "
        read REGISTRY_USERNAME
    done

    while [ -z "$REGISTRY_PASSWORD" ]; do
        printf "Password: "
        read -s REGISTRY_PASSWORD
    done
    echo
fi

echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USERNAME}" --password-stdin
