# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Get Base Sha
description: Gets base commit sha for comparison

outputs:
  base-sha:
    description: Returns the commit sha sha
    value: ${{ steps.sha.outputs.base_sha }}

runs:
  using: composite
  steps:
    - name: Get Base Sha
      shell: bash
      id: sha
      env:
        GH_EVENT_BEFORE: ${{ github.event.before }}
      run: |
        ref_name=$(echo "${GITHUB_REF}" | awk -F'/' '{print $2}')
        exit_code=$?
        previous_sha=
        if [ "${ref_name}" = "tags" ]; then
          previous_tag=$(git rev-parse "$(git tag --sort=-v:refname | head -n 2 | tail -n 1)") && exit_code=$? || exit_code=$?
          previous_sha=$(git rev-list -n 1 "${previous_tag}") && exit_code=$? || exit_code=$?
        else
          if [ -n "${GH_EVENT_BEFORE}" ]; then
            previous_sha="${GH_EVENT_BEFORE}" && exit_code=$? || exit_code=$?
          else
            previous_sha=$(git rev-list -n 1 "HEAD^") && exit_code=$? || exit_code=$?
          fi
        fi
        if [ $exit_code -eq 0 -a -n "${previous_sha}" ]; then
          echo "base_sha=${previous_sha}" >> $GITHUB_OUTPUT
        fi
