# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Get Branch Name
description: Gets the branch name

outputs:
  branch-name:
    description: Returns the branch name
    value: ${{ steps.refs.outputs.branch_name }}

runs:
  using: composite
  steps:
    - name: Show Refs
      shell: bash
      id: refs
      env:
        REF_NAME: ${{ github.ref_name }}
        WORKFLOW_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
      run: |
        if [ -n "$WORKFLOW_HEAD_BRANCH" ]; then
          echo "branch_name=${WORKFLOW_HEAD_BRANCH}" >> $GITHUB_OUTPUT
        elif [ -n "$REF_NAME" ]; then
          echo "branch_name=${REF_NAME}" >> $GITHUB_OUTPUT
        fi
