# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Get Changed Files
description: Get a list of the changed files

outputs:
  changed-files:
    description: "Whether to build parent image first"
    value: ${{ steps.get-changed.outputs.changedFilesVar }}
  changed-files-json:
    description: "Whether to build parent image first JSON"
    value: ${{ steps.get-changed.outputs.changedFilesJsonVar }}

runs:
  using: composite
  steps:
    - name: Get Changed Files
      id: get-changed
      shell: bash
      run: |
        changedFiles=$(echo $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }}))
        echo "changedFilesVar=${changedFiles}" >> $GITHUB_OUTPUT
        for f in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }}); do
          changedFilesJson=",\"${f}\""
        done
        changedFilesJson="$(echo $changedFilesJson | sed 's/^,//')"
        echo "::set-output name=changedFilesJsonVar::$(echo "[${changedFilesJson}]")"
