name: Build and Publish

on:
  push:
    tags:
      - 'v*'
      - 'latest'
    paths:
      - 'conf/**'
      - 'docker/**'

concurrency: ${{ github.event.workflow_run.head_branch || github.ref_name || github.head_ref || github.ref }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_base: ${{ steps.changed-files.outputs.any_changed }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files matching filter
        id: changed-files
        uses: ./.github/actions/changed-files-action
        with:
          since_last_remote_commit: true
          files: |
            conf/base/*.env
            docker/dockerfiles/*.base
            docker/bin/*-base*.sh
            docker/bin/gh-login

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Github Event
        run: echo '${{ toJson(github.event) }}'
      - name: Workflow Run
        run: echo '${{ tojson(github.event.workflow_run) }}'
      - name: Show Changed Matches
        run: echo '${{ needs.setup.outputs.all_changed_files }}'
      - name: Show Outputs
        run: echo '${{ toJson(needs.setup.outputs) }}'
      - name: Concurrency Group
        run: echo '${{ github.event.workflow_run.head_branch || github.ref_name || github.head_ref || github.ref }}'

  docker:
    runs-on: ubuntu-latest
    needs: [setup, check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU, Docker Buildx, and Login
        uses: ./.github/actions/setup-docker-buildx-action
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Base
        if: needs.setup.outputs.build_base == 'true'
        uses: ./.github/actions/build-script-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-parent: true
          build-latest: ${{ needs.setup.outputs.build_latest }}
          debug: ${{ needs.setup.outputs.build_dev }}

      - name: Build and Push Main
        uses: ./.github/actions/build-script-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # TODO
      # - name: Main - Build and Push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: docker
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     file: docker/dockerfiles/Dockerfile.main
      #     push: true
      #     tags: user/app:latest
