name: Build and Publish

on:
  workflow_run:
    workflows: [Build and Publish Base]
    types: [completed]

  push:
    tags:
      - 'v*'
    paths:
      - 'conf/**'
      - 'docker/**'
      - '!conf/base/*'
      - '!docker/dockerfiles/*.base'

concurrency: ${{ github.event.workflow_run.head_branch || github.ref_name || github.head_ref || github.ref }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_base: ${{ steps.changed-files.outputs.any_changed }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files matching filter
        id: changed-files
        uses: ./.github/actions/changed-files-action
        with:
          files: |
            conf/base/*.env
            docker/dockerfiles/*.base

  show:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Github Event
        run: echo '${{ toJson(github.event) }}'
      - name: Workflow Run
        run: echo '${{ tojson(github.event.workflow_run) }}'
      - name: Show Changed Matches
        run: echo '${{ needs.setup.outputs.all_changed_files }}'
      - name: Show Outputs
        run: echo '${{ toJson(needs.setup.outputs) }}'
      - name: Show Refs
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.event.workflow_run.head_branch: ${{ github.event.workflow_run.head_branch }}"
      - name: Concurrency Group
        run: echo '${{ github.event.workflow_run.head_branch || github.ref_name || github.head_ref || github.ref }}'

  docker:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.workflow_run.conclusion == 'success' || !needs.setup.outputs.build_base || needs.setup.outputs.build_base == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name:
        uses: ./.github/actions/setup-docker-buildx-action
        with:
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Main
        uses: ./.github/actions/build-script-action
        with:
          docker-login: false

      # TODO
      # - name: Main - Build and Push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: docker
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     file: docker/dockerfiles/Dockerfile.main
      #     push: true
      #     tags: user/app:latest

