name: Build and Publish - Debug

on:
  workflow_run:
    workflows: [Build and Publish Base - Debug]
    types: [completed]

  push:
    branches:
      - main
    paths:
      - 'conf/**'
      - 'docker/**'
      - '!conf/base/*'
      - '!docker/dockerfiles/*.base'

concurrency: ${{ github.head_ref || github.ref }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_base: ${{ steps.changed-files.outputs.any_changed }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            conf/base/*.env
            docker/dockerfiles/*.base

  show:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Github Event
        run: echo '${{ toJson(github.event) }}'
      - name: Workflow Run
        run: echo '${{ tojson(github.event.workflow_run) }}'
      - name: Show Changed Matches
        run: |
          echo "${{ toJson(needs.setup.outputs.all_changed_files) }}"
      - name: Show Outputs
        run: echo '${{ toJson(needs.setup.outputs) }}'
      name: Show Refs
      run: |
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "github.ref: ${{ github.ref }}"

  docker:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event.workflow_run.conclusion == 'success' || !needs.setup.outputs.build_base
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Main
        uses: ./.github/actions/build-push-script-action
        with:
          debug: true
          docker-login: false
