name: Build and Publish

on:
  push:
    branches:
      - main
    # paths:
    #   - 'conf/**'
    #   - 'docker/**'

env:
  DEBUG: "true"
  BUILD_BASE: "false"

jobs:
  docker-debug:
    if: env.DEBUG == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Base - Build and Push
        if: env.BUILD_BASE == 'true'
        uses: ./.github/actions/build-push-script-action
        with:
          build-parent: true

      - name: Main - Build and Push
        uses: ./.github/actions/build-push-script-action

      # TODO
      # - name: Base - Build and Push
      #   if: env.BUILD_BASE == 'true'
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: docker
      #     platforms: linux/amd64
      #     file: docker/dockerfiles/Dockerfile.base
      #     push: true
      #     tags: user/app:latest

      # TODO
      # - name: Main - Build and Push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: docker
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      #     file: docker/dockerfiles/Dockerfile.main
      #     push: true
      #     tags: user/app:latest
