name: Build and Publish Base - Debug

on:
  push:
    branches:
      - main
    paths:
      - 'conf/base/*.env'
      - 'docker/dockerfiles/Dockerfile.base'

concurrency: ${{ github.event.workflow_run.head_branch || github.ref_name || github.head_ref || github.ref }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Base
        uses: ./.github/actions/build-push-script-action
        with:
          build-parent: true
          debug: true
          docker-login: false
